---
title: "Flash Card Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill 
    resize_reload: false
    css: style.css
runtime: shiny
---

```{r setup, include=FALSE}
library(here)
library(flexdashboard)
here::i_am('flexFlashCard.Rmd')
sfiles <- list.files(here('R'), pattern = '.R', recursive = TRUE)
spaths <- file.path(here('R'), sfiles)
sapply(spaths, source)
rm(sfiles, spaths)

deck <- mod_load_deck_server('load_deck')
card <- mod_browse_deck_server('browse_deck', deck$data$topic)
mod_show_card_server('show_card', card$data)
```

Interact with Flash Cards
========================================================================

Column {data-width=300}
-----------------------------------------------------------------------

### Load Flash Cards from Excel File {data-height=250}
```{r}
mod_load_deck_ui('load_deck')
```

### Browse Flash Cards in Selected Topics {data-height=750}

```{r}
mod_browse_deck_ui('browse_deck')
```

Column {data-width=700}
-----------------------------------------------------------------------

### Selected Flash Card

```{r}
mod_show_card_ui('show_card')
```

